'use strict'
import {
  GraphQLFloat,
  GraphQLList,
  GraphQLObjectType,
  GraphQLString
} from 'graphql'
import R from 'ramda'
import User from '../users/type'
import { getByID } from '../users/data'

export default new GraphQLObjectType({
  description: `An animal`,
  fields: () => ({
    adopt_fee: {
      description: `What does it cost to adopt this animal, in US dollars.`,
      type: GraphQLFloat
    },
    age: {
      description: `How old is this animal, number of months.`,
      type: GraphQLFloat
    },
    breed: {
      description: `If this animal is commonly categorized within its species, how so?`,
      type: GraphQLString
    },
    color: {
      description: `A generic list of colors that best describe this animal.`,
      type: new GraphQLList(GraphQLString)
    },
    date_available: {
      description: `What is the earliest this animal can be adopted?`,
      type: GraphQLString
    },
    description: {
      description: `A short paragraph or two from the humane society about this animal's personality.`,
      type: GraphQLString
    },
    followers: {
      description: `A list of users that have marked this animal as a favorite`,
      resolve: animal => Promise.all(
        R.map(getByID,
        R.keys(
          R.prop(`followers`)(animal)))),
      type: new GraphQLList(User)
    },
    id: {
      description: `A unique identifier for this animal in the humane society database.`,
      type: GraphQLString
    },
    image_url: {
      description: `A URL to the entry image hosted by the humane society.`,
      type: GraphQLString
    },
    name: {
      description: `The animal's given name. Sometimes auto-generated by the Humane Society.`,
      type: GraphQLString
    },
    sex: {
      description: `The anatomical sex of the animal, if known.`,
      type: GraphQLString
    },
    species: {
      description: `The biological species of the animal.`,
      type: GraphQLString
    },
    weight: {
      description: `The weight of the animal in English pounds, if known.`,
      type: GraphQLFloat
    }
  }),
  name: `Animal`
})
