'use strict'
import {
  GraphQLList,
  GraphQLObjectType,
  GraphQLString
} from 'graphql'
import Animal from '../animals/type'
import Resolvers from './resolvers'

export default new GraphQLObjectType({
  description: `A user`,
  fields: () => ({
    id: {
      description: `A unique identifier for this animal in the humane society database.`,
      type: GraphQLString
    },
    name: {
      description: `The animal's given name. Sometimes auto-generated by the Humane Society.`,
      type: GraphQLString
    },
    watching: {
      description: `Animals this user is currently watching.`,
      resolve: Resolvers.watching,
      type: new GraphQLList(Animal)
    }
  }),
  name: `User`
})
